asnp *sh*
Dismount-SPContentDatabase "SP_Content_WLK-Connect_UAT"
Dismount-SPContentDatabase "SP_Content_ATLAS_UAT-TMP"
Dismount-SPContentDatabase "SP_Content_BI-Portal_UAT"
Dismount-SPContentDatabase "SP_Content_ATLAS-IS_UAT"
Dismount-SPContentDatabase "SP_Content_TIP_UAT"
#Dismount-SPContentDatabase "SP_Content_ATLAS_UAT" # Does not exist
Dismount-SPContentDatabase "SP_Content_MasterDataMgmt_UAT"
Dismount-SPContentDatabase "SP_Content_PDA_UAT"
Dismount-SPContentDatabase "SP_Content_WLK-Collab_UAT"
Dismount-SPContentDatabase "SP_Content_SAP_UAT"
Dismount-SPContentDatabase "SP_Content_Collab_Teams-Restored_UAT"
#Dismount-SPContentDatabase "SP_Content_Blank_UAT" # Does not exist
Dismount-SPContentDatabase "SP_Content_Contracts_UAT"
#Dismount-SPContentDatabase "SP_Content_EDMS_UAT" # Does not exist
Dismount-SPContentDatabase "SP_Content_SharePointIntranet_UAT"
Dismount-SPContentDatabase "SP_Content_O365-ARCHIVES_UAT"
Dismount-SPContentDatabase "SP_Content_CorpAccting_UAT"
Dismount-SPContentDatabase "SP_Content_BuildingProducts_UAT"
Dismount-SPContentDatabase "SP_Content_Chemicals_UAT"
Dismount-SPContentDatabase "SP_Content_Corp_Coms_UAT"
Dismount-SPContentDatabase "SP_Content_CSR_UAT"
Dismount-SPContentDatabase "SP_Content_EHSS_UAT"
Dismount-SPContentDatabase "SP_Content_Finance_UAT"
Dismount-SPContentDatabase "SP_Content_HR_UAT"
Dismount-SPContentDatabase "SP_Content_Legal_UAT"
Dismount-SPContentDatabase "SP_Content_PCDocs_UAT"
Dismount-SPContentDatabase "SP_Content_Natrium_Pub_UAT"
Dismount-SPContentDatabase "SP_Content_AIM_Plants_UAT"
Dismount-SPContentDatabase "SP_Content_Royal_Portal_UAT"
Dismount-SPContentDatabase "SP_Content_RBP_UAT"
Dismount-SPContentDatabase "SP_Content_SPD_UAT"
Dismount-SPContentDatabase "SP_Content_TradeCompliance_UAT"
Dismount-SPContentDatabase "SP_Content_MySites_UAT"
Dismount-SPContentDatabase "SP_Content_OneIT-Europe_UAT"
Dismount-SPContentDatabase "SP_Content_SearchCente_UAT"
Dismount-SPContentDatabase "SP_Content_Vinnolit_UAT"
Dismount-SPContentDatabase "WSS_Content_1db67448-66eb-46f0-a07d-693effd16ece"
Dismount-SPContentDatabase "WSS_Content_EDMS-PRD"
Dismount-SPContentDatabase "WSS_Content_SAP-PRD"
Dismount-SPContentDatabase "WSS_Content_SearchCenter-PRD"
Dismount-SPContentDatabase "WSS_Content_e774041f-b91a-43d7-9c47-21164f8e92c5"

#Dismount-SPContentDatabase "WSS_Content_ATLAS-PRD"  # Already Done
