test-spcontentdatabase WSS_Content_WLK-Connect-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_WLK-Connect-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_ATLAS-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_ATLAS-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_ATLAS-PRD-TMP | Out-File -FilePath E:\Scripts\Output\WSS_Content_ATLAS-PRD-TMP_TestResults.txt
test-spcontentdatabase WSS_Content_ATLAS-IS-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_ATLAS-IS-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_MasterDataMgmt-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_MasterDataMgmt-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_PDA-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_PDA-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_BI-Portal-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_BI-Portal-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_COE-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_COE-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_TIP-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_TIP-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_WLK-Collab-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_WLK-Collab-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Collab_Teams-Restored-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Collab_Teams-Restored-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Collab_Teams-2 | Out-File -FilePath E:\Scripts\Output\WSS_Content_Collab_Teams-2_TestResults.txt
test-spcontentdatabase WSS_Content_SAP-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_SAP-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Contracts-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Contracts-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_EDMS-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_EDMS-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_SharePointIntranet | Out-File -FilePath E:\Scripts\Output\WSS_Content_SharePointIntranet_TestResults.txt
test-spcontentdatabase WSS_Content_CorpAccting | Out-File -FilePath E:\Scripts\Output\WSS_Content_CorpAccting_TestResults.txt
test-spcontentdatabase WSS_Content_AIM_Plants-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_AIM_Plants-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Legal-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Legal-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_SPD-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_SPD-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Finance-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Finance-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_BuildingProducts-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_BuildingProducts-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Corp_Coms-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Corp_Coms-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_EHSS-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_EHSS-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_HR-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_HR-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_PCDocs-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_PCDocs-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_TradeCompliance-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_TradeCompliance-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Royal_Portal-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Royal_Portal-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_CSR-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_CSR-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Chemicals-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Chemicals-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Natrium_Pub-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Natrium_Pub-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_O365-ARCHIVES | Out-File -FilePath E:\Scripts\Output\WSS_Content_O365-ARCHIVES_TestResults.txt
test-spcontentdatabase WSS_Content_RBP-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_RBP-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_MySites-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_MySites-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_OneIT-Europe-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_OneIT-Europe-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_SearchCenter-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_SearchCenter-PRD_TestResults.txt
test-spcontentdatabase WSS_Content_Vinnolit-PRD | Out-File -FilePath E:\Scripts\Output\WSS_Content_Vinnolit-PRD_TestResults.txt